version: '3'

services:
  nginx:
    image: 651706751476.dkr.ecr.us-east-2.amazonaws.com/bloom/prism-nginx
    restart: unless-stopped
    env_file:
      - ./.nginx-certbot.env
    ports:
      - 80:80
      - 443:443
    volumes:                                    # Storage can be either a
      - nginx_secrets:/etc/letsencrypt          # Docker managed volume (see list at the bottom)
  api-service:
    image: 651706751476.dkr.ecr.us-east-2.amazonaws.com/bloom/prism-api-service
    restart: unless-stopped
    env_file:
      - ./.api-service.env
  cors-anywhere:
    image: yasinuslu/cors-anywhere:latest
    restart: unless-stopped
    ports:
       - 80

volumes:
  nginx_secrets:
