# Generated by Django 3.1.7 on 2021-03-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stripe_payment", "0002_auto_20210303_1333"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stripecustomer",
            name="subscription_id",
            field=models.TextField(null=True),
        ),
    ]
