# Generated by Django 3.1.7 on 2021-05-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stripe_payment", "0004_licensepurchase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licensepurchase",
            name="customer_id",
            field=models.TextField(null=True),
        ),
    ]
