# Generated by Django 3.1.7 on 2021-05-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stripe_payment", "0005_auto_20210504_1315"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stripecustomer",
            name="subscription_id",
            field=models.TextField(blank=True, null=True),
        ),
    ]
