# Generated by Django 3.1.7 on 2023-03-23 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0007_stripeconnectaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripeconnectaccount',
            name='user',
        ),
        migrations.AddField(
            model_name='stripeconnectaccount',
            name='ac_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stripeconnectaccount',
            name='account_type',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stripeconnectaccount',
            name='user_id',
            field=models.TextField(blank=True, db_index=True),
        ),
    ]
