# Generated by Django 3.1.7 on 2023-09-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0008_auto_20230323_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeconnectaccount',
            name='info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
