# Generated by Django 3.1.7 on 2021-05-04 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("referral", "0002_auto_20210503_1324"),
    ]

    operations = [
        migrations.AddField(
            model_name="commission",
            name="event_id",
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="referral",
            name="user",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
