"""add rejected to post

Revision ID: 118ea92f6375
Revises: a5a4e15d3637
Create Date: 2025-02-13 14:48:20.062845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '118ea92f6375'
down_revision = 'a5a4e15d3637'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rejected', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_post_rejected'), ['rejected'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_rejected'))
        batch_op.drop_column('rejected')

    # ### end Alembic commands ###
