"""add approved to post

Revision ID: 32fa5335c5c3
Revises: 118ea92f6375
Create Date: 2025-02-13 14:51:39.400499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32fa5335c5c3'
down_revision = '118ea92f6375'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved', sa.Boolean(), nullable=True))
        batch_op.drop_index('ix_post_rejected')
        batch_op.create_index(batch_op.f('ix_post_approved'), ['approved'], unique=False)
        batch_op.drop_column('rejected')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rejected', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_post_approved'))
        batch_op.create_index('ix_post_rejected', ['rejected'], unique=False)
        batch_op.drop_column('approved')

    # ### end Alembic commands ###
