"""Add label indices

Revision ID: 434d0d180ac2
Revises: e1221cda78a7
Create Date: 2025-01-26 13:24:26.934656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '434d0d180ac2'
down_revision = 'e1221cda78a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('label', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('confidence', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('post_id', sa.BigInteger(), nullable=False))
        batch_op.create_index('idx_label_type_confidence_post_id', ['label_type', 'confidence', 'post_id'], unique=False)
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('label', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('idx_label_type_confidence_post_id')
        batch_op.drop_column('post_id')
        batch_op.drop_column('confidence')
        batch_op.drop_column('value')

    # ### end Alembic commands ###
