"""add videos field in submission

Revision ID: 4793e043b155
Revises: a6fd56a92afa
Create Date: 2025-02-13 14:05:10.445403

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4793e043b155'
down_revision = 'a6fd56a92afa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('label', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.String(), nullable=True))

    with op.batch_alter_table('post_submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('videos', sa.JSON(), nullable=True))
        batch_op.drop_column('vodeos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vodeos', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_column('videos')

    with op.batch_alter_table('label', schema=None) as batch_op:
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
