"""add submission

Revision ID: 68b8ecc890de
Revises: 434d0d180ac2
Create Date: 2025-02-12 13:28:49.366409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68b8ecc890de'
down_revision = '434d0d180ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uri', sa.String(), nullable=False),
    sa.Column('submitter', sa.String(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_submission'))
    )
    with op.batch_alter_table('post_submission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_submission_submitter'), ['submitter'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_submission_uri'), ['uri'], unique=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('e_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('e_conf', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('i_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('i_conf', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('a_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('a_conf', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('modality', sa.Integer(), nullable=True))
        batch_op.alter_column('cid',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_post_modality'), ['modality'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_modality'))
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('cid',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('modality')
        batch_op.drop_column('a_conf')
        batch_op.drop_column('a_score')
        batch_op.drop_column('i_conf')
        batch_op.drop_column('i_score')
        batch_op.drop_column('e_conf')
        batch_op.drop_column('e_score')

    with op.batch_alter_table('post_submission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_submission_uri'))
        batch_op.drop_index(batch_op.f('ix_post_submission_submitter'))

    op.drop_table('post_submission')
    # ### end Alembic commands ###
