"""unique uri submission remove index

Revision ID: a4274f432e44
Revises: 532bbc764aed
Create Date: 2025-02-17 13:43:23.160579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4274f432e44'
down_revision = '532bbc764aed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_submission', schema=None) as batch_op:
        batch_op.drop_index('ix_post_submission_uri')
        batch_op.create_unique_constraint(batch_op.f('uq_post_submission_uri'), ['uri'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_submission', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_post_submission_uri'), type_='unique')
        batch_op.create_index('ix_post_submission_uri', ['uri'], unique=True)

    # ### end Alembic commands ###
