"""approved at to review at field in submission

Revision ID: a5a4e15d3637
Revises: 4793e043b155
Create Date: 2025-02-13 14:25:16.031729

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a5a4e15d3637'
down_revision = '4793e043b155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('approved_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('reviewed_at')

    # ### end Alembic commands ###
