"""add ondelete cascade to label

Revision ID: c027b719298d
Revises: 32fa5335c5c3
Create Date: 2025-02-14 20:38:19.715943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c027b719298d'
down_revision = '32fa5335c5c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('label', schema=None) as batch_op:
        batch_op.drop_constraint('fk_label_post_id_post', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_label_post_id_post'), 'post', ['post_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('label', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_label_post_id_post'), type_='foreignkey')
        batch_op.create_foreign_key('fk_label_post_id_post', 'post', ['post_id'], ['id'])

    # ### end Alembic commands ###
