"""Add label model

Revision ID: e1221cda78a7
Revises: 4afb1444ab79
Create Date: 2025-01-26 12:34:57.707735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1221cda78a7'
down_revision = '4afb1444ab79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('label',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('label_type', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('src', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('label', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_label_label_type'), ['label_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('label', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_label_label_type'))

    op.drop_table('label')
    # ### end Alembic commands ###
