"""add metadata field in submission

Revision ID: f4c149bbc146
Revises: 68b8ecc890de
Create Date: 2025-02-12 15:36:20.464280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4c149bbc146'
down_revision = '68b8ecc890de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_submission', schema=None) as batch_op:
        batch_op.drop_column('data')
        batch_op.drop_column('text')

    # ### end Alembic commands ###
