# Generated by Django 3.2 on 2021-05-01 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210407_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='campaign',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='http_referer',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='invite_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referrer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
