# Generated by Django 3.1.7 on 2022-04-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20220404_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignemailrecord',
            name='opened',
            field=models.DateTimeField(null=True),
        ),
    ]
