# Generated by Django 3.1.7 on 2022-04-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_campaignemailrecord_opened'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignemailrecord',
            name='open_headers',
            field=models.JSONField(null=True),
        ),
    ]
