# Generated by Django 3.1.7 on 2022-08-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_customuser_unsubscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='deactivated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
