# Generated by Django 3.1.7 on 2023-03-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_customuser_deactivated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
